export const ADD_COMMENT = 'ADD_COMMENT';
export const FIND_COMMENT = 'FIND_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const UPDATE_COMMENTS = 'UPDATE_COMMENTS';
export const DELTEL_COMMENT = 'DELTEL_COMMENT';
export const DELTEL_GET_COMMENT = 'DELTEL_GET_COMMENT';
export const DELTEL_FETCH_COMMENT = 'DELTEL_FETCH_COMMENT';

export const GET_COMMENT = 'GET_COMMENT';
export const FETCH_COMMENT = 'FETCH_COMMENT';
export const FETCH_ADD_COMMENT = 'FETCH_ADD_COMMENT';

export const SHOW_FETCH_COMMENTS = 'SHOW_FETCH_COMMENTS';

export const PAGINATION_PAGE = 'PAGINATION_PAGE';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const FETCH_ACTION = 'FETCH_ACTION';